### PR TITLE
latest

### PR DESCRIPTION
**Pull request by Rickol91**

### CODE REVIEW

**Comment by david-04** [comment]
Hey Ricky. I trust that this was not your intention, but your pull request comes across as a bit offensive.

Daniel Alberski wrote this quiz engine, generously releasing it under an open-source license, allowing everyone to use it and create derivative works. I have added comparatively little to the fork that I created. I predominantly made minor UI improvements and productionized the application into an npm package, allowing others to easily install and use it.

Your pull request now tries to rebrand the application, giving it a different name, and having your own name displayed on the start page and in the browser tab. You have made changes to less than 1% of the code base. Your pull request suggests that I continue maintaining the application while keeping your name front and center, giving the impression that you are the author of it all.

As stated before, I trust that this is not the spirit/intention in which you created the pull request.

You are more than welcome to fork this repository and modify/rebrand it (in your fork) as you see fit. You're also welcome to publish your version on npm if you want to make it available to others.

If you believe that rebranding is a useful feature, I'm also happy to accept a pull request. However, the default name and branding need to remain unchanged. You could add configuration parameters to `quiz-mate.cfg`. There could be one parameter for the page title/message on the start page, and one where users can configure their preferred background image. The default configuration (that's created during the first start) would not contain these values. The parameters would be commented out. If so, the current/default Quiz Mate branding would apply. If people wish to customize the branding, they could do so by editing the configuration file.

If you want to pursue/discuss this further, feel free to open an issue in this repository or continue the conversation right here.

I'm closing this pull request now.

**Comment by Rickol91** [comment]
Hi David,

Indeed not my intention at all, I just wanted to give it a personal touch
to play it with my family and strictly personal only. And to be honest I
try to figure out how to code so I used this project as a bit of study
material, sorry if it let you think that I was stealing it. Trying to learn
how to code from scratch is a though learning path so I got my own Linux
VPS running docker containers, reverse proxies and stuff and so I came
across your Github project and found it interesting to pick it up. Anyways
I respect the policy and will not continue to change it.

With kind regards,

Rick

Sent from Gmail Mobile


Op za 6 jul 2024 om 08:44 schreef David Hofmann ***@***.***>

**Comment by david-04** [comment]
All good, Rick. No offense was taken. I would also like to apologize. In hindsight, I can see that my previous message probably came across somewhat intimidating. This was not my intention.

And to avoid any misunderstanding: All that you have done is perfectly in line with the license. You're welcome (and encouraged!) to fork the repository, customize it in whichever way you like, and also put your name on it. There's absolutely nothing wrong with that. The license does not impose any restrictions. You could even use your fork commercially and try to sell it for money. It would not breach the license.

When you make changes just for yourself, keep them in your own fork. A pull request is only needed when you have made changes that you want to contribute back to the main project, so that everyone can benefit from them.

Good luck with our journey to learn how to code!

**Comment by Rickol91** [comment]
Hey David!

Thanks, I think we understand each others point of view :) maybe we can
team-up to add some intresting features (if you like) BTW have you tried
the new www.websim.ai its a fun concept where you give prompts and AI makes
a simulation of it, its real cool.

Maybe a cool addon to Quiz-mate is adding a youtube video where the
attendees need to answer questions based on the attached video, dont know
if something like iframe is working with Json, Im trying to find out.

Cheers!

Rick

Sent from Gmail Mobile


Op ma 8 jul 2024 om 11:24 schreef David Hofmann ***@***.***>

**Pull request closed without merging**
